# Generated by Django 4.0.3 on 2022-04-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_org', models.TextField(max_length=300)),
                ('date', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('ticket_info', models.TextField(max_length=100)),
                ('social_media', models.CharField(max_length=100)),
            ],
        ),
    ]
