# Generated by Django 4.0.3 on 2022-04-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_org',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='social_media',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_info',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
