# Generated by Django 4.0.3 on 2022-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_event_name_event_location_event_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='tag_choices',
            field=models.CharField(choices=[('free', 'free'), ('academic', 'academic'), ('athletic', 'athletic'), ('food', 'food'), ('cultural', 'cultural')], max_length=8, null=True),
        ),
    ]
