# Generated by Django 4.0.3 on 2022-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_event_tags_event_tag_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag_choices',
        ),
        migrations.AddField(
            model_name='event',
            name='tag_choice',
            field=models.CharField(choices=[('Cultural', 'cultural'), ('Academic', 'academic'), ('Sports', 'sports'), ('Tech', 'tech'), ('Theater', 'theater'), ('Music', 'music'), ('Arts', 'arts')], max_length=10, null=True),
        ),
    ]
