# Generated by Django 4.0.3 on 2022-04-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_event_tag_choices_event_tag_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag_choice',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
